'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating style prompts to inspire users.
 *
 * The flow takes no input and returns a list of style prompts.
 * - generateStylePrompts - A function that handles the generation of style prompts.
 * - GenerateStylePromptsOutput - The return type for the generateStylePrompts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateStylePromptsOutputSchema = z.object({
  stylePrompts: z
    .array(z.string())
    .describe('An array of style prompts to inspire users.'),
});
export type GenerateStylePromptsOutput = z.infer<typeof GenerateStylePromptsOutputSchema>;

export async function generateStylePrompts(): Promise<GenerateStylePromptsOutput> {
  return generateStylePromptsFlow({});
}

const prompt = ai.definePrompt({
  name: 'stylePromptGenerationPrompt',
  output: {schema: GenerateStylePromptsOutputSchema},
  prompt: `You are a style inspiration generator.  Your job is to
  create a list of different style prompts that can be used to
  generate images.  These prompts should be diverse and inspire
  creativity.  Return them as a JSON array of strings.  Here are some examples:

  - "Steampunk"
  - "Art Deco"
  - "Pop Art"
  - "Cyberpunk"
  - "Renaissance"
  - "Impressionism"
  - "Cubism"
  - "Abstract Expressionism"
  - "Minimalism"
  - "Surrealism"
  - "Gothic"
  - "Baroque"
  - "Art Nouveau"
  - "Bauhaus"
  - "Constructivism"
  - "Fauvism"
  - "Expressionism"
  - "Dadaism"
  - "Futurism"
  - "Suprematism"
  - "Romanticism"
  - "Realism"
  - "Neoclassicism"
  - "Rococo"
  - "Victorian"
  - "Edwardian"
  - "Modernism"
  - "Postmodernism"
  - "Contemporary"
  - "Vintage"
  - "Retro"
  - "Bohemian"
  - "Rustic"
  - "Industrial"
  - "Scandinavian"
  - "Mediterranean"
  - "Tropical"
  - "Asian"
  - "African"
  - "Middle Eastern"
  - "South American"
  - "Indigenous"
  - "Fantasy"
  - "Sci-Fi"
  - "Horror"
  - "Thriller"
  - "Comedy"
  - "Drama"
  - "Action"
  - "Adventure"
  - "Mystery"
  - "Western"
  - "Historical"
  - "Musical"
  - "Animation"
  - "Documentary"
  - "Experimental"
  - "Avant-Garde"
  - "Street Art"
  - "Graffiti"
  - "Mural"
  - "Mosaic"
  - "Collage"
  - "Photomontage"
  - "Digital Art"
  - "3D Art"
  - "Pixel Art"
  - "Vector Art"
  - "Typography"
  - "Calligraphy"
  - "Illustration"
  - "Sketch"
  - "Drawing"
  - "Painting"
  - "Sculpture"
  - "Ceramics"
  - "Glass Art"
  - "Textile Art"
  - "Metal Art"
  - "Wood Art"
  - "Paper Art"
  - "Installation Art"
  - "Performance Art"
  - "Land Art"
  - "Environmental Art"
  - "Bio Art"
  - "Sound Art"
  - "Light Art"
  - "Kinetic Art"
  - "Interactive Art"
  - "Net Art"
  - "Software Art"
  - "Generative Art"
  - "Algorithmic Art"
  - "Fractal Art"
  - "Glitch Art"
  - "Vaporwave"
  - "Synthwave"
  - "Outrun"
  - "Retrowave"
  - "Chillwave"
  - "Darkwave"
  - "New Wave"
  - "Coldwave"
  - "Minimal Wave"
  - "Italo Disco"
  - "Eurobeat"
  - "Trance"
  - "House"
  - "Techno"
  - "Drum and Bass"
  - "Dubstep"
  - "Grime"
  - "Garage"
  - "Jungle"
  - "Breakbeat"
  - "Hardcore"
  - "Gabber"
  - "Speedcore"
  - "Noise"
  - "Ambient"
  - "Drone"
  - "Classical"
  - "Opera"
  - "Jazz"
  - "Blues"
  - "Rock"
  - "Metal"
  - "Punk"
  - "Grunge"
  - "Alternative"
  - "Indie"
  - "Folk"
  - "Country"
  - "Electronic"
  - "Hip Hop"
  - "Rap"
  - "Pop"
  - "Reggae"
  - "Ska"
  - "Funk"
  - "Soul"
  - "R&B"
  - "Disco"
  - "Latin"
  - "World"
  - "Gospel"
  - "Spiritual"
  - "Chanson"
  - "Klezmer"
  - "Polka"
  - "Waltz"
  - "Tango"
  - "Samba"
  - "Rumba"
  - "Mambo"
  - "Cha-Cha"
  - "Salsa"
  - "Merengue"
  - "Cumbia"
  - "Reggaeton"
  - "Bossa Nova"
  - "Flamenco"
  - "Fado"
  - "Celtic"
  - "Nordic"
  - "Slavic"
  - "Balkan"
  - "Gypsy"
  - "African"
  - "Middle Eastern"
  - "Asian"
  - "Indigenous"
  - "Abstract"
  - "Geometric"
  - "Organic"
  - "Biomorphic"
  - "Surreal"
  - "Fantasy"
  - "Sci-Fi"
  - "Horror"
  - "Thriller"
  - "Comedy"
  - "Drama"
  - "Action"
  - "Adventure"
  - "Mystery"
  - "Western"
  - "Historical"
  - "Musical"
  - "Animation"
  - "Documentary"
  - "Experimental"
  - "Avant-Garde"
  - "Street Art"
  - "Graffiti"
  - "Mural"
  - "Mosaic"
  - "Collage"
  - "Photomontage"
  - "Digital Art"
  - "3D Art"
  - "Pixel Art"
  - "Vector Art"
  - "Typography"
  - "Calligraphy"
  - "Illustration"
  - "Sketch"
  - "Drawing"
  - "Painting"
  - "Sculpture"
  - "Ceramics"
  - "Glass Art"
  - "Textile Art"
  - "Metal Art"
  - "Wood Art"
  - "Paper Art"
  - "Installation Art"
  - "Performance Art"
  - "Land Art"
  - "Environmental Art"
  - "Bio Art"
  - "Sound Art"
  - "Light Art"
  - "Kinetic Art"
  - "Interactive Art"
  - "Net Art"
  - "Software Art"
  - "Generative Art"
  - "Algorithmic Art"
  - "Fractal Art"
  - "Glitch Art"
  - "Vaporwave"
  - "Synthwave"
  - "Outrun"
  - "Retrowave"
  - "Chillwave"
  - "Darkwave"
  - "New Wave"
  - "Coldwave"
  - "Minimal Wave"
  - "Italo Disco"
  - "Eurobeat"
  - "Trance"
  - "House"
  - "Techno"
  - "Drum and Bass"
  - "Dubstep"
  - "Grime"
  - "Garage"
  - "Jungle"
  - "Breakbeat"
  - "Hardcore"
  - "Gabber"
  - "Speedcore"
  - "Noise"
  - "Ambient"
  - "Drone"
  - "Classical"
  - "Opera"
  - "Jazz"
  - "Blues"
  - "Rock"
  - "Metal"
  - "Punk"
  - "Grunge"
  - "Alternative"
  - "Indie"
  - "Folk"
  - "Country"
  - "Electronic"
  - "Hip Hop"
  - "Rap"
  - "Pop"
  - "Reggae"
  - "Ska"
  - "Funk"
  - "Soul"
  - "R&B"
  - "Disco"
  - "Latin"
  - "World"
  - "Gospel"
  - "Spiritual"
  - "Chanson"
  - "Klezmer"
  - "Polka"
  - "Waltz"
  - "Tango"
  - "Samba"
  - "Rumba"
  - "Mambo"
  - "Cha-Cha"
  - "Salsa"
  - "Merengue"
  - "Cumbia"
  - "Reggaeton"
  - "Bossa Nova"
  - "Flamenco"
  - "Fado"
  - "Celtic"
  - "Nordic"
  - "Slavic"
  - "Balkan"
  - "Gypsy"
  - "African"
  - "Middle Eastern"
  - "Asian"
  - "Indigenous"

  Return 20 diverse style prompts in JSON format.`, // Removed Handlebars since there is no input
});

const generateStylePromptsFlow = ai.defineFlow(
  {
    name: 'generateStylePromptsFlow',
    inputSchema: z.object({}),
    outputSchema: GenerateStylePromptsOutputSchema,
  },
  async () => {
    const {output} = await prompt({});
    return output!;
  }
);
